### ISSUE TITLE
Doesn't seem to work at all

### ISSUE THREAD

**Issue by dhacherl** [TheAmazingBrianPowell/OnBotStudio#1]
I installed and enabled the plugin, but it seems not to function.  No button, no functionality, no nothing.  Version info is:
Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 1, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 16
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: net.rhsrobotics.OnBotStudio (1.0), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40)

Screenshot showing installed plugin and lack of button attached
<img width="1262" alt="Screenshot 2022-02-20 111848" src="https://user-images.githubusercontent.com/22875066/154860342-c57753ad-1ecb-4093-adbe-e5ba16a583f3.png">
.

**Comment by TheAmazingBrianPowell** [comment]
Did you open the console labeled OnBotStudio towards the bottom of Android Studio? That would be where the compile button would be located and the log

**Comment by dhacherl** [comment]
Thanks. I didn't see that, but Android studio is a giant visual mess. I'll check it out when I get back to my dev box.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dhacherl** [comment]
Ah!  Over on the far left.  I'm an infrequent user of Android Studio without good reflexes as to where to look and was so focused on the lower right that I didn't see it.  [Invisible gorillas](http://www.theinvisiblegorilla.com/gorilla_experiment.html) again.
